export const foods = [
  {
    id: 1,
    type: 'burgers',
    title: 'BBQ Burger',
    image: '/burger-bbq.png',
    price: 5.6,
  },
  {
    id: 2,
    type: 'burgers',
    title: 'Cheese Burger',
    image: '/burger-cheeseburger.png',
    price: 5.2,
  },
  {
    id: 3,
    type: 'burgers',
    title: 'Texas Squealer Burger',
    image: '/burger-texas-squealer.png',
    price: 6.2,
  },
  {
    id: 4,
    type: 'burgers',
    title: 'Turkey Burger',
    image: '/burger-turkey.png',
    price: 6.8,
  },
  {
    id: 5,
    type: 'drinks',
    title: 'Lemon Juice',
    image: '/lemon-juice.png',
    price: 2.4,
  },
  {
    id: 6,
    type: 'drinks',
    title: 'Mango Juice',
    image: '/mango-juice.png',
    price: 2.2,
  },
  {
    id: 7,
    type: 'drinks',
    title: 'Orange Juice',
    image: '/orange-juice.png',
    price: 2.3,
  },
  {
    id: 8,
    type: 'drinks',
    title: 'Soursop Juice',
    image: '/soursop-juice.png',
    price: 2.1,
  },
  {
    id: 9,
    type: 'pasta',
    title: 'Pasta Sugo',
    image: '/pasta-sugo.png',
    price: 11.6,
  },
  {
    id: 10,
    type: 'pasta',
    title: 'Pasta Spaghetti',
    image: '/pasta-spaghetti.png',
    price: 12,
  },
  {
    id: 11,
    type: 'pasta',
    title: 'Pasta Italy',
    image: '/pasta-italy.png',
    price: 10.8,
  },
  {
    id: 12,
    type: 'pasta',
    title: 'Pasta Neo',
    image: '/pasta-neo.png',
    price: 12.6,
  },
  {
    id: 13,
    type: 'pizza',
    title: 'Pizza Four Cheese',
    image: '/pizza-four-cheese.png',
    price: 5.4,
  },
  {
    id: 14,
    type: 'pizza',
    title: 'Pizza Mozzarella',
    image: '/pizza-mozzarella.png',
    price: 5.7,
  },
  {
    id: 15,
    type: 'pizza',
    title: 'Pizza Pepperoni',
    image: '/pizza-pepperoni.png',
    price: 5.5,
  },
  {
    id: 16,
    type: 'pizza',
    title: 'Pizza Portuguese',
    image: '/pizza-portuguese.png',
    price: 5.2,
  },
  {
    id: 17,
    type: 'soup',
    title: 'Soup Chilli',
    image: '/soup-chilli.png',
    price: 5,
  },
  {
    id: 18,
    type: 'soup',
    title: 'Soup Mix',
    image: '/soup-mix.png',
    price: 6,
  },
  {
    id: 19,
    type: 'soup',
    title: 'Soup Pumpkin',
    image: '/soup-pumpkin.png',
    price: 5.6,
  },
  {
    id: 20,
    type: 'soup',
    title: 'Soup Tomato',
    image: '/soup-tomato.png',
    price: 7,
  },
  {
    id: 21,
    type: 'sushi',
    title: 'Sushi Kola',
    image: '/sushi-kola.png',
    price: 9.3,
  },
  {
    id: 22,
    type: 'sushi',
    title: 'Sushi Oma',
    image: '/sushi-oma.png',
    price: 8.5,
  },
  {
    id: 23,
    type: 'sushi',
    title: 'Sushi Otaca',
    image: '/sushi-otaca.png',
    price: 8.1,
  },
  {
    id: 24,
    type: 'sushi',
    title: 'Sushi Temaki Nakayoshi',
    image: '/sushi-temaki-nakayoshi.png',
    price: 12.6,
  },
]
